[package]
name = "nes-emu-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.3"
hashbrown = "0.16.0"
# sdl2 = { version = "0.36.0", features = ["bundled"] }
sdl2 = "0.38.0"
rand = "0.7.3"
